name:                khronos-vulkan-tutorial-haskell
version:             0.1.0.0
github:              "heitor-lassarote/khronos-vulkan-tutorial-haskell"
license:             BSD-3-Clause
author:              "Heitor Toledo Lassarote de Paula"
maintainer:          "heitortoledo at hotmail dot com"
copyright:           "2026 Heitor Toledo Lassarote de Paula"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Haskell reimplementation of the Khronos Vulkan Tutorial
category:            Graphics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/heitor-lassarote/khronos-vulkan-tutorial-haskell#readme>

build-type: Custom

custom-setup:
  dependencies:
  - base
  - Cabal
  - process

dependencies:
- base >= 4.7 && < 5

default-extensions:
- BlockArguments
- ConstraintKinds
- DataKinds
- DeriveAnyClass
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- LambdaCase
- LexicalNegation
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoFieldSelectors
- OverloadedRecordDot
- OverloadedStrings
- PatternSynonyms
- RecordWildCards
- ScopedTypeVariables
- StandaloneKindSignatures
- StrictData
- TupleSections
- TypeApplications
- TypeData
- TypeFamilies
- ViewPatterns

ghc-options:
- -Werror
- -Weverything
- -Wno-all-missed-specialisations
- -Wno-ambiguous-fields
- -Wno-implicit-prelude
- -Wno-missed-specialisations
- -Wno-missing-import-lists
- -Wno-missing-role-annotations
- -Wno-missing-safe-haskell-mode
- -Wno-monomorphism-restriction
- -Wno-unsafe

library:
  source-dirs: src
  c-sources:
  - cbits/debug_callback.c
  dependencies:
  - bytestring
  - filepath
  - GLFW-b
  - hashable
  - integer-logarithms
  - JuicyPixels
  - lens
  - linear
  - monad-loops
  - mtl
  - resourcet
  - time
  - unliftio
  - unordered-containers
  - vector
  - vulkan
  - wavefront

executables:
  khronos-vulkan-tutorial-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - khronos-vulkan-tutorial-haskell

tests:
  khronos-vulkan-tutorial-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - khronos-vulkan-tutorial-haskell
